package com.health.secondbrain.notify

import android.Manifest
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.content.pm.PackageManager
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import com.health.secondbrain.R
import com.health.secondbrain.data.ActiveAlertSummary
import org.json.JSONObject

class DemoNotifications(private val context: Context) {

    fun sendAlert(alert: ActiveAlertSummary): Boolean {
        ensureChannel()
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU &&
            ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED
        ) {
            Log.w(TAG, "POST_NOTIFICATIONS permission is not granted; active alert persisted without a notification.")
            return false
        }

        val evidence = JSONObject(alert.evidenceJson)
        val heartRate = evidence.optDouble("heart_rate_bpm", Double.NaN)
            .takeUnless { it.isNaN() }
            ?.toInt()
        val title = if (alert.severity == "high") "HALO cardiac alert" else "HALO strain alert"
        val text = heartRate?.let { "Heart rate spike detected at $it bpm. Slow down and check symptoms." }
            ?: "Cardiac strain signal detected. Slow down and review HALO evidence."
        val notification = NotificationCompat.Builder(context, CHANNEL_ID)
            .setSmallIcon(R.mipmap.ic_launcher)
            .setContentTitle(title)
            .setContentText(text)
            .setStyle(NotificationCompat.BigTextStyle().bigText("$text Evidence source: ${alert.source}."))
            .setPriority(NotificationCompat.PRIORITY_HIGH)
            .setAutoCancel(true)
            .build()
        NotificationManagerCompat.from(context).notify(alert.id.hashCode(), notification)
        return true
    }

    fun ensureChannel() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        val manager = context.getSystemService(NotificationManager::class.java)
        val channel = NotificationChannel(
            CHANNEL_ID,
            "HALO watch alerts",
            NotificationManager.IMPORTANCE_HIGH,
        ).apply {
            description = "Realtime watch alerts generated by the HALO backend path."
        }
        manager.createNotificationChannel(channel)
    }

    companion object {
        private const val TAG = "DemoNotifications"
        private const val CHANNEL_ID = "halo_watch_alerts"
    }
}
